version: '3.8'

services:
  app:
    image: rent
    build:
      context: .
    ports:
      - "5132:5000"
    volumes:
      - ./doc_result:/apartments-app/doc_result
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

volumes:
  doc_result:
    driver: local
